config/routes.rb
Rails.application.routes.draw do
  root 'donors#show'
  
  devise_for :donors

  resources :donations, :only => [:create]
  resources :physical_donations, :only => [:create]
  resources :voucher_donations, :only => [:create]
  resources :experience_donations, :only => [:create]

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor
  belongs_to :donation_type, polymorphic: true

  validates_presence_of :donor, :donation_type, :title, :description
  validates_associated :donation_type
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :donations
end

app/models/experience_donation.rb
class ExperienceDonation < ActiveRecord::Base
  has_one :donation, as: :donation_type
  has_one :donor, :through => :donation

  validates_presence_of :latitude, :longitude
end

app/models/physical_donation.rb
class PhysicalDonation < ActiveRecord::Base
  has_one :donation, as: :donation_type
  has_one :donor, :through => :donation

  validates_presence_of :height, :width, :weight
end

app/models/voucher_donation.rb
class VoucherDonation < ActiveRecord::Base
  has_one :donation, as: :donation_type
  has_one :donor, :through => :donation

  validates_presence_of :expiration_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_donor!

  def create
    donation = Donation.create(donation_params)
    donation.donor = current_donor

    case params[:donation_type]
    when "physical"
      pd = PhysicalDonation.new(physical_params)
      donation.donation_type = pd
    when "voucher"
      vd = VoucherDonation.new(voucher_params)
      donation.donation_type = vd
    when "experience"
      ed = ExperienceDonation.new(experience_params)
      donation.donation_type = ed
    end
    current_donor.donations << donation
    redirect_to :controller => :donors, :action => :show and return
  end

  private
  def physical_params
    params[:donation].require(:physical_donation).permit(:height, :width, :weight)
  end

  def voucher_params
    params[:donation].require(:voucher_donation).permit(:expiration_date)
  end

  def experience_params
    params[:donation].require(:experience_donation).permit(:contact, :latitude, :longitude)
  end

  def donation_params
    params.require(:donation).dup.except!(:physical_donation, :voucher_donation, :experience_donation).permit(:title, :description)
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :authenticate_donor!

  def show
    @donor = current_donor
    return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
  def render_donation_type(donation_type)
    if donation_type.is_a?(PhysicalDonation)
      render(:partial => "donations/physical", :object => donation_type)
    elsif donation_type.is_a?(VoucherDonation)
      render(:partial => "donations/voucher", :object => donation_type)
    elsif donation_type.is_a?(ExperienceDonation)
      render(:partial => "donations/experience", :object => donation_type)
    end
  end
end

app/views/donations/_experience.html.erb
Donated Experience<br>
<span>Contact: <%= experience.contact %></span><br>
<span>Latitude: <%= experience.latitude %></span><br>
<span>Longitude: <%= experience.longitude %></span><br>

app/views/donations/_location_list.html.erb
<script type="text/javascript">
  <% list = location_list.select{|donation| donation.donation_type.is_a?(ExperienceDonation)} %>
  <% if not list.empty? %>
    var experience_donations = 
      <%# TODO: this is an XSS bug, better to write a json_safe or load the data a different way %>
      <%= list.to_json(:include => :donation_type).html_safe %>
    ;
  <% end %>
</script>

app/views/donations/_physical.html.erb
Donated Physical Object<br>
height: <%= physical.height %>cm<br>
width: <%= physical.width %>cm<br>
weight: <%= physical.weight %>kg<br>

app/views/donations/_voucher.html.erb
Donated Voucher<br>
Expires: <%= voucher.expiration_date %>

app/views/donors/show.html.erb
Welcome, <%= @donor.email %>
<%= link_to "Sign out", destroy_donor_session_path, :method => :delete %>

<%= form_for Donation.new do |d| %>
    <%= d.label :title %>
    <%= d.text_field :title %><br>
    <%= d.label :description %>
    <%= d.text_field :description %><br>
    Type of Donation:
    <!-- set up radio button to select between the 3 different donation types (and their forms) -->
    <%= radio_button_tag(:donation_type, "physical") %><%= label_tag(:donation_type_physical, "Physical") %>
    <%= radio_button_tag(:donation_type, "voucher") %><%= label_tag(:donation_type_voucher, "Voucher") %>
    <%= radio_button_tag(:donation_type, "experience") %><%= label_tag(:donation_type_experience, "Experience") %>
    <br>
    <div id="physical" class="donation-type-form">
      <%= d.fields_for PhysicalDonation.new do |p| %>
        <%= p.label :height %>
        <%= p.text_field :height %>cm
        <%= p.label :width %>
        <%= p.text_field :width %>cm
        <%= p.label :weight %>
        <%= p.text_field :weight %>kg
      <% end %>
    </div>
    <div id="voucher" class="donation-type-form">
      <%= d.fields_for VoucherDonation.new do |v| %>
        <%= v.label :expiration_date %>
        <%= v.date_select :expiration_date %>
      <% end %>
    </div>
    <div id="experience" class="donation-type-form">
      <!-- TODO: get lat/lng from HTML geo spec -->
      <%= d.fields_for ExperienceDonation.new do |e| %>
        <%= e.label :contact %>
        <%= e.text_field :contact %>
        <%= e.label :latitude %>
        <%= e.text_field :latitude %>
        <%= e.label :longitude %>
        <%= e.text_field :longitude %>
      <% end %>
    </div>
    <%= d.submit %>
<% end %>

<h2>Where you've donated</h2>
<div id="map-canvas"></div>
<%= render(:partial => "donations/location_list", :object => current_donor.donations) %>

<h2>Donations</h2>
<div id="donations">
  <% current_donor.donations.each do |donation| %>
    <div class='donation'>
      <h3><%= donation.title %></h3>
      <span class='description'><%= donation.description %></span><br>
      <%= render_donation_type(donation.donation_type) %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCIFFZjZHZHqbD_9ow68ccAylSfPIyjpgI&sensor=true">
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>